const CLONE_CAMPAIGN_TYPE = {
  BEGIN: 'CLONE_CAMPAIGN_TYPE/FETCH_BEGIN',
  SUCCESS: 'CLONE_CAMPAIGN_TYPE/FETCH_SUCCESS',
  FAILURE: 'CLONE_CAMPAIGN_TYPE/FETCH_FAILURE',
};

export default CLONE_CAMPAIGN_TYPE;
