import {
  statsCalculatesECPC,
  statsNumberToFixed,
  statsDateFormat,
} from 'helpers/statistic/calculated';

const tableScheme = [
  {
    name: 'Date',
    field: 'day',
    id: 'date',
    prefix: '',
    sufix: '',
    numeric: false,
    order: true,
    // filters: [statsDateFormat('dd.MM.yyyy')],
    calculated: null,
    style: {},
  },
  {
    name: 'Clicks',
    field: 'clicks',
    id: 'clicks',
    prefix: '',
    sufix: '',
    numeric: true,
    order: true,
    filters: [],
    calculated: null,
    style: {},
  },
  {
    name: 'Impression',
    field: 'impressions',
    id: 'impression',
    prefix: '-',
    sufix: '',
    numeric: true,
    order: true,
    filters: [statsNumberToFixed(4)],
    calculated: [statsCalculatesECPC],
    style: {},
  },
  {
    name: 'CTR',
    field: 'ctr',
    id: 'ctr',
    prefix: '',
    sufix: '%',
    numeric: true,
    order: true,
    filters: [statsNumberToFixed(4)],
    calculated: null,
    style: {},
  },
  {
    name: 'eCPC',
    field: 'ecpc',
    id: 'ecpc',
    prefix: '',
    sufix: '',
    numeric: true,
    order: true,
    filters: [statsNumberToFixed(4)],
    calculated: null,
    style: {},
  },
  {
    name: 'eCPA',
    field: 'ecpa',
    id: 'ecpa',
    prefix: '',
    sufix: '',
    numeric: true,
    order: true,
    filters: [statsNumberToFixed(4)],
    calculated: null,
    style: {},
  },
  {
    name: 'eCPM',
    field: 'ecpm',
    id: 'ecpm',
    prefix: '',
    sufix: '',
    numeric: true,
    order: true,
    filters: [statsNumberToFixed(4)],
    calculated: null,
    style: {},
  },
];

export default tableScheme;
