const CAMPAIGN_RESOURCE_TYPES_ACTIONS = {
  BEGIN: 'CAMPAIGN_RESOURCE_TYPES_ACTIONS/FETCH_BEGIN',
  SUCCESS: 'CAMPAIGN_RESOURCE_TYPES_ACTIONS/FETCH_SUCCESS',
  FAILURE:
    'AUTH_TCAMPAIGN_RESOURCE_TYPES_ACTIONSYPE_ACTIONS/FETCH_FAILURE',
};

export default CAMPAIGN_RESOURCE_TYPES_ACTIONS;
