const CAMPAIGN_STATUS_BUTTON_ACTIONS = {
  BEGIN: 'CAMPAIGN_STATUS_BUTTON/FETCH_BEGIN',
  SUCCESS: 'CAMPAIGN_STATUS_BUTTON/FETCH_SUCCESS',
  FAILURE: 'CAMPAIGN_STATUS_BUTTON/FETCH_FAILURE',
};

export default CAMPAIGN_STATUS_BUTTON_ACTIONS;
