const AUTH_TYPES_ACTIONS = {
  BEGIN: 'AUTH_TYPE_ACTIONS/FETCH_BEGIN',
  SUCCESS: 'AUTH_TYPE_ACTIONS/FETCH_SUCCESS',
  FAILURE: 'AUTH_TYPE_ACTIONS/FETCH_FAILURE',
};

export default AUTH_TYPES_ACTIONS;
