const CAMPAIGN_PLAY_PAUSE_BUTTON_ACTIONS = {
  BEGIN: 'CAMPAIGN_PLAY_PAUSE_BUTTON/FETCH_BEGIN',
  SUCCESS: 'CAMPAIGN_PLAY_PAUSE_BUTTON/FETCH_SUCCESS',
  FAILURE: 'CAMPAIGN_PLAY_PAUSE_BUTTON/FETCH_FAILURE',
};

export default CAMPAIGN_PLAY_PAUSE_BUTTON_ACTIONS;
