const CAMPAIGN_LIST_ACTIONS = {
  BEGIN: 'CAMPAIGN_LIST_ACTIONS/FETCH_BEGIN',
  ADD_ADFORMAT: 'CAMPAIGN_LIST_ACTIONS/ADD_ADFORMAT',
  SUCCESS: 'CAMPAIGN_LIST_ACTIONS/FETCH_SUCCESS',
  SUCCESS_BY_ID: 'CAMPAIGN_LIST_ACTIONS_BY_ID/FETCH_SUCCESS',
  FAILURE: 'CAMPAIGN_LIST_ACTIONS/FETCH_FAILURE',
  ADD_CLONE: 'CAMPAIGN_LIST_ACTIONS/ADD_CLONE',
  UPDATE_ITEM: 'CAMPAIGN_LIST_ACTIONS/UPDATE_ITEM',
};

export default CAMPAIGN_LIST_ACTIONS;
