const CAMPAIGN_LIST_ACTIONS = {
  BEGIN: 'CAMPAIGN_LIST_ACTIONS/FETCH_BEGIN',
  SUCCESS: 'CAMPAIGN_LIST_ACTIONS/FETCH_SUCCESS',
  SUCCESS_BY_ID: 'CAMPAIGN_LIST_ACTIONS_BY_ID/FETCH_SUCCESS',
  FAILURE: 'CAMPAIGN_LIST_ACTIONS/FETCH_FAILURE',
};

export default CAMPAIGN_LIST_ACTIONS;
