const APPROVE_REJECT_TYPE = {
  BEGIN: 'APPROVE_REJECT_TYPE/FETCH_BEGIN',
  SUCCESS: 'APPROVE_REJECT_TYPE/FETCH_SUCCESS',
  FAILURE: 'APPROVE_REJECT_TYPE/FETCH_FAILURE',
};

export default APPROVE_REJECT_TYPE;
