const CAMPAIGN_LIST_TYPES_ACTIONS = {
  REQUEST: 'CAMPAIGN_LIST_TYPES_ACTIONS/REQUEST',
  REQUEST_MAIN_FILTER:
    'CAMPAIGN_LIST_TYPES_ACTIONS/REQUEST_MAIN_FILTER',
  REQUEST_CAMPAIGN_ID:
    'CAMPAIGN_LIST_TYPES_ACTIONS/REQUEST_CAMPAIGN_ID',
};

export default CAMPAIGN_LIST_TYPES_ACTIONS;
