export const countriesWithGroups = {
  A1: ['Tear3'],
  AD: ['GOLD BUT SMALL', 'Tear2'],
  AE: ['Arab World', 'Tear2'],
  AF: ['South Asia', 'Tear3'],
  AG: ['GOLD BUT SMALL', 'Tear3'],
  AI: ['GOLD BUT SMALL', 'Tear3'],
  AL: ['Eastern Europe & Central Asia', 'Tear3'],
  AM: ['Eastern Europe & Central Asia', 'Tear3'],
  AO: ['Africa', 'Tear3'],
  AR: ['Latin America & Caribbean', 'Tear2'],
  AS: ['GOLD BUT SMALL', 'Tear3'],
  AT: ['DACH', 'Tear1'],
  AU: ['English Speaking', 'Tear1'],
  AW: ['GOLD BUT SMALL', 'Tear3'],
  AX: ['Nordics', 'Tear3'],
  AZ: ['Eastern Europe & Central Asia', 'Tear2'],
  BA: ['Eastern Europe & Central Asia', 'Tear3'],
  BB: ['GOLD BUT SMALL', 'Tear3'],
  BD: ['South Asia', 'Tear3'],
  BE: ['BeNeLux', 'Tear1'],
  BF: ['Africa', 'Tear3'],
  BG: ['Central Europe and the Baltics', 'Tear2'],
  BH: ['Arab World', 'Tear3'],
  BI: ['Africa', 'Tear3'],
  BJ: ['Africa', 'Tear3'],
  BL: ['GOLD BUT SMALL', 'Tear3'],
  BM: ['GOLD BUT SMALL', 'Tear3'],
  BN: ['East Asia & Pacific', 'Tear3'],
  BO: ['Latin America & Caribbean', 'Tear3'],
  BQ: ['GOLD BUT SMALL', 'Tear3'],
  BR: ['Latin America & Caribbean', 'Tear2'],
  BS: ['GOLD BUT SMALL', 'Tear2'],
  BT: ['South Asia', 'Tear3'],
  BW: ['Africa', 'Tear3'],
  BY: ['Eastern Europe & Central Asia', 'Tear3'],
  BZ: ['GOLD BUT SMALL', 'Tear3'],
  CA: ['English Speaking', 'Tear1'],
  CC: ['GOLD BUT SMALL', 'Tear3'],
  CD: ['Africa', 'Tear3'],
  CF: ['Africa', 'Tear3'],
  CG: ['Africa', 'Tear3'],
  CH: ['DACH', 'Tear1'],
  CI: ['Africa', 'Tear3'],
  CK: ['GOLD BUT SMALL', 'Tear3'],
  CL: ['Latin America & Caribbean', 'Tear2'],
  CM: ['Africa', 'Tear2'],
  CN: ['Asian Tigers', 'Tear2'],
  CO: ['Latin America & Caribbean', 'Tear2'],
  CR: ['Latin America & Caribbean', 'Tear2'],
  CU: ['Latin America & Caribbean', 'Tear3'],
  CV: ['GOLD BUT SMALL', 'Tear3'],
  CW: ['GOLD BUT SMALL', 'Tear3'],
  CX: ['GOLD BUT SMALL', 'Tear3'],
  CY: ['EUMED 7', 'Tear2'],
  CZ: ['Central Europe and the Baltics', 'Tear2'],
  DE: ['DACH', 'Tear1'],
  DJ: ['Arab World', 'Tear3'],
  DK: ['Nordics', 'Tear1'],
  DM: ['GOLD BUT SMALL', 'Tear3'],
  DO: ['Latin America & Caribbean', 'Tear2'],
  DZ: ['Arab World', 'Tear3'],
  EC: ['Latin America & Caribbean', 'Tear2'],
  EE: ['Central Europe and the Baltics', 'Tear2'],
  EG: ['Arab World', 'Tear2'],
  ER: ['Africa', 'Tear3'],
  ES: ['EUMED 7', 'Tear1'],
  ET: ['Africa', 'Tear3'],
  FI: ['Nordics', 'Tear1'],
  FJ: ['East Asia & Pacific', 'Tear3'],
  FK: ['GOLD BUT SMALL', 'Tear3'],
  FM: ['GOLD BUT SMALL', 'Tear3'],
  FO: ['Nordics', 'Tear3'],
  FR: ['EUMED 7', 'Tear1'],
  GA: ['Africa', 'Tear3'],
  GB: ['English Speaking', 'Tear1'],
  SV: ['Latin America & Caribbean', 'Tear3'],
  GE: ['Eastern Europe & Central Asia', 'Tear3'],
  GF: ['GOLD BUT SMALL', 'Tear2'],
  GG: ['GOLD BUT SMALL', 'Tear3'],
  GH: ['Africa', 'Tear3'],
  GI: ['GOLD BUT SMALL', 'Tear2'],
  GL: ['Nordics', 'Tear3'],
  GM: ['Africa', 'Tear3'],
  GN: ['Africa', 'Tear3'],
  GP: ['GOLD BUT SMALL', 'Tear2'],
  GQ: ['Africa', 'Tear3'],
  GR: ['EUMED 7', 'Tear2'],
  GD: ['Latin America & Caribbean', 'Tear3'],
  GU: ['GOLD BUT SMALL', 'Tear3'],
  GW: ['Africa', 'Tear3'],
  GT: ['Latin America & Caribbean', 'Tear3'],
  HK: ['Asian Tigers', 'Tear2'],
  GY: ['Latin America & Caribbean', 'Tear3'],
  HR: ['Central Europe and the Baltics', 'Tear2'],
  HT: ['Latin America & Caribbean', 'Tear3'],
  HU: ['Central Europe and the Baltics', 'Tear2'],
  ID: ['East Asia & Pacific', 'Tear2'],
  IE: ['English Speaking', 'Tear1'],
  IL: ['GOLD BUT SMALL', 'Tear2'],
  IM: ['GOLD BUT SMALL', 'Tear2'],
  IN: ['South Asia', 'Tear3'],
  IO: ['GOLD BUT SMALL', 'Tear3'],
  IQ: ['Arab World', 'Tear3'],
  IR: ['Arab World', 'Tear3'],
  IS: ['Nordics', 'Tear2'],
  IT: ['EUMED 7', 'Tear1'],
  JE: ['GOLD BUT SMALL', 'Tear3'],
  JM: ['GOLD BUT SMALL', 'Tear3'],
  JO: ['Arab World', 'Tear3'],
  JP: ['Asian Tigers', 'Tear1'],
  KE: ['Africa', 'Tear3'],
  KG: ['Eastern Europe & Central Asia', 'Tear3'],
  KH: ['East Asia & Pacific', 'Tear3'],
  KI: ['East Asia & Pacific', 'Tear3'],
  KM: ['Arab World', 'Tear3'],
  HN: ['Latin America & Caribbean', 'Tear3'],
  KP: ['East Asia & Pacific', 'Tear3'],
  KR: ['Asian Tigers', 'Tear2'],
  KW: ['Arab World', 'Tear3'],
  KY: ['GOLD BUT SMALL', 'Tear2'],
  KZ: ['Eastern Europe & Central Asia', 'Tear2'],
  LA: ['East Asia & Pacific', 'Tear3'],
  LB: ['Arab World', 'Tear3'],
  MX: ['Latin America & Caribbean', 'Tear2'],
  LI: ['DACH', 'Tear2'],
  LK: ['South Asia', 'Tear3'],
  LR: ['Africa', 'Tear3'],
  LS: ['Africa', 'Tear3'],
  LT: ['Central Europe and the Baltics', 'Tear2'],
  LU: ['BeNeLux', 'Tear1'],
  LV: ['Central Europe and the Baltics', 'Tear2'],
  LY: ['Arab World', 'Tear3'],
  MA: ['Arab World', 'Tear2'],
  MC: ['GOLD BUT SMALL', 'Tear2'],
  MD: ['Eastern Europe & Central Asia', 'Tear3'],
  ME: ['Eastern Europe & Central Asia', 'Tear2'],
  MF: ['GOLD BUT SMALL', 'Tear3'],
  MG: ['Africa', 'Tear3'],
  MH: ['GOLD BUT SMALL', 'Tear3'],
  MK: ['Eastern Europe & Central Asia', 'Tear3'],
  ML: ['Africa', 'Tear3'],
  MM: ['East Asia & Pacific', 'Tear3'],
  MN: ['East Asia & Pacific', 'Tear3'],
  MO: ['Asian Tigers', 'Tear2'],
  MP: ['GOLD BUT SMALL', 'Tear3'],
  MQ: ['GOLD BUT SMALL', 'Tear2'],
  MR: ['Arab World', 'Tear3'],
  MS: ['GOLD BUT SMALL', 'Tear3'],
  MT: ['EUMED 7', 'Tear2'],
  MU: ['GOLD BUT SMALL', 'Tear2'],
  MV: ['GOLD BUT SMALL', 'Tear3'],
  MW: ['Africa', 'Tear3'],
  NI: ['Latin America & Caribbean', 'Tear3'],
  MY: ['East Asia & Pacific', 'Tear2'],
  MZ: ['Africa', 'Tear3'],
  NA: ['Africa', 'Tear3'],
  NC: ['GOLD BUT SMALL', 'Tear2'],
  NE: ['Africa', 'Tear3'],
  NF: ['GOLD BUT SMALL', 'Tear3'],
  NG: ['Africa', 'Tear3'],
  PA: ['Latin America & Caribbean', 'Tear3'],
  NL: ['BeNeLux', 'Tear1'],
  NO: ['Nordics', 'Tear1'],
  NP: ['South Asia', 'Tear3'],
  NR: ['East Asia & Pacific', 'Tear3'],
  NU: ['GOLD BUT SMALL', 'Tear3'],
  NZ: ['English Speaking', 'Tear1'],
  OM: ['Arab World', 'Tear3'],
  PY: ['Latin America & Caribbean', 'Tear2'],
  PE: ['Latin America & Caribbean', 'Tear2'],
  PF: ['GOLD BUT SMALL', 'Tear2'],
  PG: ['GOLD BUT SMALL', 'Tear3'],
  PH: ['East Asia & Pacific', 'Tear2'],
  PK: ['South Asia', 'Tear3'],
  PL: ['Central Europe and the Baltics', 'Tear2'],
  PM: ['GOLD BUT SMALL', 'Tear3'],
  PR: ['GOLD BUT SMALL', 'Tear2'],
  PS: ['Arab World', 'Tear3'],
  PT: ['EUMED 7', 'Tear2'],
  PW: ['East Asia & Pacific', 'Tear3'],
  KN: ['Latin America & Caribbean', 'Tear3'],
  QA: ['Arab World', 'Tear2'],
  RE: ['GOLD BUT SMALL', 'Tear2'],
  RO: ['Central Europe and the Baltics', 'Tear2'],
  RS: ['Eastern Europe & Central Asia', 'Tear2'],
  RU: ['Eastern Europe & Central Asia', 'Tear2'],
  RW: ['Africa', 'Tear3'],
  SA: ['Arab World', 'Tear2'],
  SB: ['GOLD BUT SMALL', 'Tear3'],
  SC: ['GOLD BUT SMALL', 'Tear3'],
  SD: ['Arab World', 'Tear3'],
  SE: ['Nordics', 'Tear1'],
  SG: ['Asian Tigers', 'Tear2'],
  SH: ['GOLD BUT SMALL', 'Tear3'],
  SI: ['Central Europe and the Baltics', 'Tear2'],
  SJ: ['Nordics', 'Tear3'],
  SK: ['Central Europe and the Baltics', 'Tear2'],
  SL: ['Africa', 'Tear3'],
  SM: ['GOLD BUT SMALL', 'Tear2'],
  SN: ['Africa', 'Tear3'],
  SO: ['Arab World', 'Tear3'],
  LC: ['Latin America & Caribbean', 'Tear3'],
  SS: ['Africa', 'Tear3'],
  ST: ['Africa', 'Tear3'],
  SR: ['Latin America & Caribbean', 'Tear3'],
  SX: ['GOLD BUT SMALL', 'Tear3'],
  SY: ['Arab World', 'Tear3'],
  SZ: ['Africa', 'Tear3'],
  TC: ['GOLD BUT SMALL', 'Tear3'],
  TD: ['Africa', 'Tear3'],
  TG: ['Africa', 'Tear3'],
  TH: ['East Asia & Pacific', 'Tear2'],
  TJ: ['Eastern Europe & Central Asia', 'Tear3'],
  TL: ['East Asia & Pacific', 'Tear3'],
  TM: ['Eastern Europe & Central Asia', 'Tear3'],
  TN: ['Arab World', 'Tear3'],
  TO: ['East Asia & Pacific', 'Tear3'],
  TR: ['Eastern Europe & Central Asia', 'Tear2'],
  TT: ['GOLD BUT SMALL', 'Tear3'],
  TV: ['East Asia & Pacific', 'Tear3'],
  TW: ['Asian Tigers', 'Tear2'],
  TZ: ['Africa', 'Tear3'],
  UA: ['Eastern Europe & Central Asia', 'Tear2'],
  UG: ['Africa', 'Tear3'],
  US: ['English Speaking', 'Tear1'],
  UY: ['Latin America & Caribbean', 'Tear2'],
  UZ: ['Eastern Europe & Central Asia', 'Tear3'],
  VA: ['GOLD BUT SMALL', 'Tear3'],
  VC: ['GOLD BUT SMALL', 'Tear3'],
  VE: ['Latin America & Caribbean', 'Tear3'],
  VG: ['GOLD BUT SMALL', 'Tear2'],
  VI: ['GOLD BUT SMALL', 'Tear2'],
  VN: ['East Asia & Pacific', 'Tear3'],
  VU: ['East Asia & Pacific', 'Tear3'],
  WF: ['GOLD BUT SMALL', 'Tear3'],
  WS: ['East Asia & Pacific', 'Tear3'],
  YE: ['Arab World', 'Tear3'],
  YT: ['GOLD BUT SMALL', 'Tear3'],
  ZA: ['English Speaking', 'Tear1'],
  ZM: ['Africa', 'Tear3'],
  ZW: ['Africa', 'Tear3'],
};

export const countriesGroups = [
  { name: 'Tear1', count: 21 },
  { name: 'Tear2', count: 69 },
  { name: 'Tear3', count: 151 },
  null,
  { name: 'Africa', count: 40 },
  { name: 'Arab World', count: 23 },
  { name: 'Asian Tigers', count: 7 },
  { name: 'BeNeLux', count: 3 },
  { name: 'Central Europe and the Baltics', count: 11 },
  { name: 'DACH', count: 4 },
  { name: 'East Asia & Pacific', count: 20 },
  { name: 'Eastern Europe & Central Asia', count: 18 },
  { name: 'English Speaking', count: 7 },
  { name: 'EUMED 7', count: 7 },
  { name: 'GOLD BUT SMALL', count: 59 },
  { name: 'Latin America & Caribbean', count: 25 },
  { name: 'Nordics', count: 9 },
  { name: 'South Asia', count: 7 },
];
